/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Front;

import Back.Procesos;
import javax.swing.JLabel;

/**
 *
 * @author alanm
 */


public class Visual extends javax.swing.JFrame {
 
    Procesos procesos = new Procesos(this );
    
    /**
     * Creates new form Visual
     */
    public Visual() {
        
        initComponents();
        
       
    }
    
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tenedor0 = new javax.swing.JLabel();
        tenedor1 = new javax.swing.JLabel();
        tenedor2 = new javax.swing.JLabel();
        tenedor3 = new javax.swing.JLabel();
        tenedor4 = new javax.swing.JLabel();
        filosofo0 = new javax.swing.JLabel();
        filosofo1 = new javax.swing.JLabel();
        filosofo2 = new javax.swing.JLabel();
        filosofo3 = new javax.swing.JLabel();
        filosofo4 = new javax.swing.JLabel();
        mesa = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tenedor0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/palo.png"))); // NOI18N
        jPanel1.add(tenedor0, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        tenedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/palo.png"))); // NOI18N
        jPanel1.add(tenedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        tenedor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/palo.png"))); // NOI18N
        jPanel1.add(tenedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        tenedor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/palo.png"))); // NOI18N
        jPanel1.add(tenedor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        tenedor4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/palo.png"))); // NOI18N
        jPanel1.add(tenedor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        filosofo0.setForeground(new java.awt.Color(185, 133, 81));
        filosofo0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/filosofo1.png"))); // NOI18N
        filosofo0.setText("Filosofo 0");
        filosofo0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filosofo0.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(filosofo0, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        filosofo1.setForeground(new java.awt.Color(255, 0, 0));
        filosofo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/filosofo1.png"))); // NOI18N
        filosofo1.setText("Filosofo1");
        filosofo1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        filosofo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filosofo1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(filosofo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        filosofo2.setBackground(new java.awt.Color(51, 255, 51));
        filosofo2.setForeground(new java.awt.Color(51, 204, 0));
        filosofo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/filosofo1.png"))); // NOI18N
        filosofo2.setText("Filosofo 2");
        filosofo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filosofo2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(filosofo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        filosofo3.setForeground(new java.awt.Color(153, 0, 153));
        filosofo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/filosofo1.png"))); // NOI18N
        filosofo3.setText("Filosofo 3");
        filosofo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filosofo3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(filosofo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        filosofo4.setForeground(new java.awt.Color(0, 0, 204));
        filosofo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/filosofo1.png"))); // NOI18N
        filosofo4.setText("Filosofo 4");
        filosofo4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filosofo4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(filosofo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        mesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mesa (1).png"))); // NOI18N
        jPanel1.add(mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 250, -1));

        jButton1.setText("iniciar Proceso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         procesos.startProcess(new JLabel[]{filosofo0,filosofo1,filosofo2,filosofo3,filosofo4},new JLabel[]{tenedor0,tenedor1,tenedor2,tenedor3,tenedor4});
         
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel filosofo0;
    private javax.swing.JLabel filosofo1;
    private javax.swing.JLabel filosofo2;
    private javax.swing.JLabel filosofo3;
    private javax.swing.JLabel filosofo4;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mesa;
    private javax.swing.JLabel tenedor0;
    private javax.swing.JLabel tenedor1;
    private javax.swing.JLabel tenedor2;
    private javax.swing.JLabel tenedor3;
    private javax.swing.JLabel tenedor4;
    // End of variables declaration//GEN-END:variables
}
